services:
  app:
    build:
      context: .
      target: final
    ports:
      - "${APP_LOCAL_PORT}:${APP_CONTAINER_PORT}"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres 
  postgres:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_LOCAL_PORT}:${POSTGRES_CONTAINER_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:

